apiVersion: v1
data:
  apiToken: ZHQwYzAxLk5ZTUNFVE00UVRFMlk2SVVWNVQ2WkxJVC5MSk5USUVINU1PTElVWk1BTFZBSEVJN1FRSFBZNUlaTUhFVjdBRFZTNUNDQ0c0V0pGM0NBU1FWNVZGUkpKRVJL
  dataIngestToken: ZHQwYzAxLkNFSzRRQ0xJT1lDU09FSFZFT1RWRlBGNy40Sk5NM1FHRElQNUsyWFNITTNPRFlaVk5FRUVDWldWUFk1NEJKQ09PWFpBUzU2NzZUVjVXSURKQ0s1UFlRM1RR
kind: Secret
metadata:
  name: eks-k8s-2026-02-13-1770987862
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: eks-k8s-2026-02-13-1770987862
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://slf17536.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - debugging
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
